### PR TITLE
Alfresco 6.2.1 support

### LINKED ISSUE #20: Alfresco 6.2.1 support
Alfred Telemetry currently doesn't work Alfresco EE 6.2.1.

**Root cause:**
Alfresco has upgraded the versions of the Micrometer libraries. This version (1.3.5) has incompatible API changes in comparison with the version used in Alfred Telemetry (1.0.6).

```
root@7f786aefcb61:/usr/local/tomcat/webapps/alfresco/WEB-INF/lib# ll | grep micro  
-rw-r--r-- 1 root root   353551 Apr 21 17:46 micrometer-core-1.0.6.jar
-rw-r--r-- 1 root root   473522 May 12 11:39 micrometer-core-1.3.5.jar
-rw-r--r-- 1 root root    16832 May 25 15:16 micrometer-jvm-extras-0.1.2.jar
-rw-r--r-- 1 root root     9561 May 25 15:16 micrometer-registry-graphite-1.0.6.jar
-rw-r--r-- 1 root root     3685 May 25 15:16 micrometer-registry-jmx-1.0.6.jar
-rw-r--r-- 1 root root    24735 May 25 15:16 micrometer-registry-prometheus-1.0.6.jar
-rw-r--r-- 1 root root    25865 May 12 11:39 micrometer-registry-prometheus-1.3.5.jar
```

**Stacktrace** (one of the many):
```
[ALFRESCO] 2020-05-27 06:43:50,612  ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alfred-telemetry.Care4AlfMeterBinderRegistrar' defined in class path resource [alfresco/module/alfred-telemetry-platform/context/binder-context.xml]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: 'void io.micrometer.core.instrument.Meter$Id.<init>(java.lang.String, java.lang.Iterable, java.lang.String, java.lang.String, io.micrometer.core.instrument.Meter$Type)'
```

### PR DESCRIPTION
**Pull request by kerkhofsd**
Closes #20

Including these changes, Alfred Telemetry seems to work on Alfresco 6.2.1.. 

There still is a Micrometer version conflict (Alfred Telemetry 1.0.6 vs Alfresco 1.3.5) for which we me might / should introduce a more pragmatic solution. 
When running Alfresco 6.2.1 now, there are two versions of the micrometer jar's in the `WEB-INF/lib` folder. As long as they're more or less compatible this workaround works fine.

### CODE REVIEW

File: alfred-telemetry-platform/src/main/java/eu/xenit/alfred/telemetry/binder/solr/sharding/SolrShardingMetricsContainer.java [hunk 1]
```diff
@@ -17,7 +18,7 @@
 public class SolrShardingMetricsContainer {
 
     private ShardRegistry shardRegistry;
-    private HashMap<Floc, HashMap<Shard, HashSet<ShardState>>> rawData;
+    private Map<Floc, HashMap<Shard, HashSet<ShardState>>> rawData;
```
Comment (kerkhofsd) [inline alfred-telemetry-platform/src/main/java/eu/xenit/alfred/telemetry/binder/solr/sharding/SolrShardingMetricsContainer.java:21]: FYI: required because the return type of `ShardRegistry#getFlocs()` changed from `HashMap<>` to `Map<>`:
https://github.com/Alfresco/alfresco-community-repo/blob/1eeac685614e8dce4f7d94535e73d6f6dd9a6930/repository/src/main/java/org/alfresco/repo/index/shard/ShardRegistry.java#L56
(And we should program towards the interface anyway.)

Comment (thijslemmens) [reply alfred-telemetry-platform/src/main/java/eu/xenit/alfred/telemetry/binder/solr/sharding/SolrShardingMetricsContainer.java:21]: Oh yes, this was possible even before Alfresco changed the return type.

**Review by thijslemmens — APPROVED** [review]
